apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-backend
  namespace: quiz-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-backend
  template:
    metadata:
      labels:
        app: quiz-backend
    spec:
      containers:
        - name: quiz-backend
          image: atakowiec/k8s-quiz:backend
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "root"
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: DB_NAME
              value: "quiz_database"
            - name: CLIENT_URL
              value: "https://quiz.cieszczyk.pl"