services:
  quiz_database:
    image: mysql:latest
    container_name: quiz_database
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: quiz_database
      MYSQL_USER: quiz_user
      MYSQL_PASSWORD: pass
      TZ: Europe/Warsaw
    volumes:
      - ./database:/var/lib/mysql
      - ./sampleDb.sql:/docker-entrypoint-initdb.d/sampleDb.sql
  quiz_phpmyadmin:
    image: phpmyadmin
    container_name: quiz_phpmyadmin
    environment:
      PMA_HOST: quiz_database
      PMA_PORT: 3306
      UPLOAD_LIMIT: 300M
    ports:
      - "5500:80"
    depends_on:
      - quiz_database
  prometheus:
    image: prom/prometheus:v2.54.1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - nprometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=365d"
  grafana:
    image: grafana/grafana:11.2.2
    ports:
      - "3333:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    depends_on:
      - prometheus
  quiz_backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: quiz_backend
    environment:
      - JWT_SECRET=asdasdsadas23waede2adq2adad2wadad2ad2ad2a3d2ad2ad3adawsdsad32ad2ada2dad2ada2d2adad2ad
      - JWT_EXPIRES_IN=365d
      - DB_HOST=quiz_database
      - DB_PORT=3306
      - DB_NAME=quiz_database
      - DB_USER=quiz_user
      - DB_PASS=pass
      - DB_SYNCHRONIZE=true
      - CLIENT_URL=quiz_frontend
      - TZ=Europe/Warsaw
      - DEFAULT_NUMBER_OF_ROUNDS=5
      - DEFAULT_QUESTIONS_PER_ROUND=5
      - DEFAULT_CATEGORIES_PER_VOTING=10
      - DEFAULT_TIME_FOR_ANSWER=20
      - MAX_PLAYERS=49
      - VOTING_TIME=10
      - SELECTED_CATEGORY_TIME_FIRST=4
      - SELECTED_CATEGORY_TIME=2
      - QUESTION_RESULT_TIME=5
    ports:
      - "3000:3000"
  quiz_frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: quiz_frontend
    environment:
      - VITE_API_URL=http://localhost:3000
      - VITE_IMG_UPLOAD_URL=https://img.cieszczyk.pl/upload
    ports:
      - "5173:80"
    volumes:
      - type: bind
        source: frontend/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - quiz_backend
volumes:
  nprometheus_data:
  grafana_data:


