global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: quiz-service
    metrics_path: /metrics
    static_configs:
      - targets: [ 'quiz_backend:3000' ]
  - job_name: 'node-exporter'
    static_configs:
      - targets: [ 'node-exporter:9100' ]
