apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-sql
  namespace: quiz-app
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS quiz_database;
    USE quiz_database;

    CREATE USER 'quiz_user'@'%' IDENTIFIED WITH mysql_native_password BY '3TRFTttgye4tg43w';
    GRANT ALL PRIVILEGES ON quiz_database.* TO 'quiz_user'@'%';
    FLUSH PRIVILEGES;
